name: CI

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 6 * * *' # 11 PM PST is 6 AM UTC
      
# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read
  checks: write

# Cancel in-progress runs on same branch
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - name: Build
        run: npm run build

  full-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.ref == 'refs/heads/master'
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
        timeout-minutes: 30